#!/usr/bin/bash

jobfile=$(mktemp -u /tmp/singularitybuild.$USER.XXXXXX)
trap "rm -f $jobfile" 0 2 3 15
sinteractive -a $jobfile -j singularity-build -p interactive -t 1:00:00 -c 4 -m 8000 -d 64
srun $(cat $jobfile) -- bash -c '
SINGULARITY_TMPDIR=$TMPDIR \
singularity pull $@' -- $@
